---
- user:
    name: "{{ target_user }}"
    password: $6$JUol7TVO$jj/1oh8Qh92eybn/PE//U77AxU4GjPSXW7gUpEDF3oGbJGhbLjMy/V5VZvE83fy946yMmAoDjGZWVDIB9Ygl2.
    groups: "sudo"
    state: present
    shell: /bin/bash
- file:
    path: "~{{target_user}}/.ssh"
    state: directory
    owner: "{{target_user}}"
