---
- name: Update cache
  apt: update_cache=yes

- name: Install xrdp
  apt: name={{ item }} state=present
  with_items:
    - xrdp

- name: Install xfce4
  apt: name={{ item }} state=present
  with_items:
    - xfce4

- name: Configure xrdp with xfce
  template:
    src: xsession
    dest: "~{{target_user}}/.xsession"
    owner: "{{target_user}}"
    group: "{{target_user}}"

- name: Restart xrdp service
  service: name=xrdp state=restarted

- name: Start vncserver to create files
  sudo: yes
  sudo_user: "{{target_user}}"
  shell: yes 'interview' | vncserver

- name: Add xstartup script
  template:
    src: xstartup
    dest: "~{{target_user}}/.vnc/xstartup"

- name: Add passwd file
  template:
    src: passwd
    dest: "~{{target_user}}/.vnc/passwd"

- name: Add sessman_passwd file
  template:
    src: passwd
    dest: "~{{target_user}}/.vnc/sessman_interview_passwd"

- name: Add xrdp.ini file
  template:
    src: xrdp-ini
    dest: "/etc/xrdp/xrdp.ini"
    owner: "xrdp"
    group: "xrdp"

- name: Stop vncserver process
  sudo: yes
  sudo_user: "{{target_user}}"
  shell: 'vncserver -kill :1'

- name: Start vncserver to create files
  sudo: yes
  sudo_user: "{{target_user}}"
  shell: yes 'interview' | vncserver
