---
- name: Create .ssh directory
  file: path="~{{ target_user }}/.ssh" state=directory

- name: Add ssh key for git access
  copy: src="~/.ssh/{{ item }}" dest="~{{ target_user }}/.ssh/{{ item }}" mode=0600 owner="{{ target_user }}"
  with_items:
    - id_rsa.pub
    - id_rsa
  when: stage is defined

- name: Build interview stage content
  git: repo="ssh://git@rs-tools.jarvellis.com:/home/git/interview-stage-{{ stage }}.git"
        dest="~{{ target_user }}/Workspace" key_file="~{{ target_user }}/.ssh/id_rsa"
        accept_hostkey=True
  sudo: yes
  sudo_user: "{{ target_user }}"
  when: stage is defined

