---
- name: Update cache
  apt: update_cache=yes

- name: Install LXDE desktop
  apt: name={{ item }} state=latest
  with_items:
    - lxde

- name: Install x2go pre-requisites
  apt: name='python-software-properties'

- name: Add x2go repository
  apt_repository: repo='ppa:x2go/stable'

- name: Install x2go server
  apt: name={{ item }} state=latest
  with_items:
  - x2goclient
  - x2goserver-xsession
  - x2golxdebindings

- name: Set SSH to use port 443 for x2go
  replace: dest=/etc/ssh/sshd_config regexp='^Port 22$' replace='Port 443'

- name: Restart ssh service
  service: name=ssh state=restarted
