---
- name: Build server
  hosts: localhost
  roles:
    - cloudserver

- name: Add interview user
  hosts: rax-cloudserver
  roles:
    - interview_user

- name: Add cloud credentials
  hosts: rax-cloudserver
  roles:
    - cloud_credentials

- name: Install and configure editors
  hosts: rax-cloudserver
  roles:
    - vim
    - emacs
    - sublime

- name: Install and configure languages
  hosts: rax-cloudserver
  roles:
    - python
    - ruby

- name: Install X Windows
  hosts: rax-cloudserver
  roles:
    - x_desktop

- name: Build interview content
  hosts: rax-cloudserver
  roles:
    - interview_stages
