---
- name: Build server
  hosts: localhost
  roles:
    - cloudserver

- name: Configure interview user
  hosts: rax-cloudserver
  tasks:
  - user:
      name: "{{target_user}}"
      password: $6$JUol7TVO$jj/1oh8Qh92eybn/PE//U77AxU4GjPSXW7gUpEDF3oGbJGhbLjMy/V5VZvE83fy946yMmAoDjGZWVDIB9Ygl2.
      state: present
      shell: /bin/bash
  - file:
      path: "~{{target_user}}/.ssh"
      state: directory
      owner: "{{target_user}}"

- name: Add cloud credentials
  hosts: rax-cloudserver
  roles:
    - cloud_credentials

- name: Install and configure editors
  hosts: rax-cloudserver
  roles:
    - vim
    - emacs
    - sublime

- name: Install and configure languages
  hosts: rax-cloudserver
  roles:
    - python
    - ruby

- name: Install X Windows
  hosts: all
  roles:
    - xfce
